<?php

declare(strict_types=1);

namespace Tests\Integration;

use App\Core\Infrastructure\Web\Routing\Router;
use PHPUnit\Framework\TestCase;

/**
 * Test that controllers without explicit route names work correctly
 */
class AutoGeneratedRouteNamesTest extends TestCase
{
    private Router $router;

    protected function setUp(): void
    {
        $this->router = new Router();
    }

    public function testExampleControllerHasAutoGeneratedRouteNames(): void
    {
        $this->router->registerController(\App\Core\Infrastructure\Web\Controller\ExampleController::class);

        // Verify auto-generated route names
        $this->assertEquals('/example', $this->router->url('example.index'));
        $this->assertEquals('/example/about', $this->router->url('example.about'));
    }

    public function testAutoGeneratedRouteWithParameter(): void
    {
        $this->router->registerController(\App\Core\Infrastructure\Web\Controller\ExampleController::class);

        $url = $this->router->url('example.show', ['id' => '123']);
        $this->assertEquals('/example/123', $url);
    }

    public function testAllExistingControllersStillWorkWithExplicitNames(): void
    {
        // These controllers have explicit names and should continue working
        $this->router->registerController(\App\Core\Infrastructure\Web\Controller\HomeController::class);
        $this->router->registerController(\App\CRM\Infrastructure\Web\Controller\PersonController::class);
        $this->router->registerController(\App\Billing\Infrastructure\Web\Controller\QuoteController::class);
        $this->router->registerController(\App\Billing\Infrastructure\Web\Controller\InvoiceController::class);

        // Verify explicit names still work
        $this->assertEquals('/', $this->router->url('home'));
        $this->assertEquals('/persons', $this->router->url('persons.index'));
        $this->assertEquals('/quotes', $this->router->url('quotes.index'));
        $this->assertEquals('/invoices', $this->router->url('invoices.index'));
    }
}
