<?php

declare(strict_types=1);

namespace Tests\Unit\Routing;

use App\Core\Infrastructure\Web\Routing\Router;
use App\Core\Infrastructure\Web\Routing\Attribute\Get;
use App\Core\Infrastructure\Web\Routing\Attribute\Post;
use App\Core\Infrastructure\Web\Controller\AbstractController;
use PHPUnit\Framework\TestCase;

/**
 * Test automatic route name generation
 */
class RouteNameGenerationTest extends TestCase
{
    private Router $router;

    protected function setUp(): void
    {
        $this->router = new Router();
    }

    public function testRouteNameIsAutoGenerated(): void
    {
        // Register a test controller without explicit route names
        $this->router->registerController(TestAutoNameController::class);

        // Verify auto-generated route names exist
        $this->assertNotNull($this->router->url('test_auto_name.index'));
        $this->assertNotNull($this->router->url('test_auto_name.create'));
        $this->assertNotNull($this->router->url('test_auto_name.store'));
    }

    public function testExplicitRouteNameTakesPrecedence(): void
    {
        // Register a controller with explicit route names
        $this->router->registerController(TestExplicitNameController::class);

        // Verify explicit names are used
        $this->assertNotNull($this->router->url('custom.name'));
    }

    public function testHomeControllerSpecialCase(): void
    {
        // Register HomeController
        $this->router->registerController(\App\Core\Infrastructure\Web\Controller\HomeController::class);

        // Should generate 'home' instead of 'home.index'
        $this->assertNotNull($this->router->url('home'));
        $this->assertEquals('/', $this->router->url('home'));
    }

    public function testPluralizedResourceNames(): void
    {
        // PersonController should generate 'persons.*'
        $this->router->registerController(\App\CRM\Infrastructure\Web\Controller\PersonController::class);

        $this->assertNotNull($this->router->url('persons.index'));
        $this->assertNotNull($this->router->url('persons.create'));
        $this->assertNotNull($this->router->url('persons.store'));
    }
}

/**
 * Test controller without explicit route names
 */
class TestAutoNameController extends AbstractController
{
    #[Get('/test')]
    public function index(): void
    {
    }

    #[Get('/test/create')]
    public function create(): void
    {
    }

    #[Post('/test')]
    public function store(): void
    {
    }
}

/**
 * Test controller with explicit route names
 */
class TestExplicitNameController extends AbstractController
{
    #[Get('/explicit', 'custom.name')]
    public function index(): void
    {
    }
}
